name: eciesdart
description: ECIES encryption for dart
version: 0.2.0

environment:
  sdk: ^3.3.1

dependencies:
  hex: ^0.2.0
  pointycastle: ^3.7.4

dev_dependencies:
  collection: ^1.18.0
  lints: ^3.0.0
  test: ^1.24.0
  bip32: ^2.0.0
  bip39: ^1.0.6
